### ISSUE TITLE
Inherted Entities

### ISSUE THREAD

**Issue by simader** [schwarzr/EFCoreBulk#1]
Hello,

All my DB-Entities inhert from a Base Class called MappedEntity. 

When I have now a `List<MappedEntity>` items, where I add the inherted entity "Picture : MappedEntity", and want to insert this list by bulkinsert. 

`await context.BulkInsertAsync(items, p => p.PropagateValues(false).IdentityInsert(true))'

an Exception is thrown.

The type Inheritance.MappedEntity is not part of the EntityFramework metadata model. Only mapped entities are supported.

**Comment by schwarzr** [comment]
This behavior is intentional.
One call To BulkInsertAsync directly creates one SqlBulkCopy and therefore all the objects provided to the method (in your case the items parameter) need to insert to the same table.

**Comment by simader** [comment]
I think I have to clarify my problem:
all my items are inserted to the same table. Only the `List<Picture>` is casted to a `List<MappedEntity>` and then your code tries to find a table "MappedEntity" which does not exist. 

I think the problem is the following line in the method GetBulkInfrstructure()
`entity = context.Model.FindEntityType(typeof(TEntity));`

instead maybe somehting like this would be more appropriate?

`entity = context.Model.FindEntityType(items.FirstOrDefault().GetType())`

Do you understand my problem?

**Comment by simader** [comment]
I did just cast it on my side before calling Bulkinsert
